basic.forever(function () {
    while (input.buttonIsPressed(Button.B)) {
        basic.showArrow(ArrowNames.North)
        basic.pause(200)
        basic.showArrow(ArrowNames.NorthWest)
        basic.pause(200)
        basic.showArrow(ArrowNames.West)
        basic.pause(200)
        basic.showArrow(ArrowNames.SouthWest)
        basic.pause(200)
        basic.showArrow(ArrowNames.South)
        basic.pause(200)
        basic.showArrow(ArrowNames.SouthEast)
        basic.pause(200)
        basic.showArrow(ArrowNames.East)
        basic.pause(200)
        basic.showArrow(ArrowNames.NorthEast)
        basic.clearScreen()
        basic.pause(1000)
    }
})
basic.forever(function () {
    while (input.buttonIsPressed(Button.A)) {
        basic.showArrow(ArrowNames.North)
        basic.pause(200)
        basic.showArrow(ArrowNames.NorthEast)
        basic.pause(200)
        basic.showArrow(ArrowNames.East)
        basic.pause(200)
        basic.showArrow(ArrowNames.SouthEast)
        basic.pause(200)
        basic.showArrow(ArrowNames.South)
        basic.pause(200)
        basic.showArrow(ArrowNames.SouthWest)
        basic.pause(200)
        basic.showArrow(ArrowNames.West)
        basic.pause(200)
        basic.showArrow(ArrowNames.NorthWest)
        basic.clearScreen()
        basic.pause(1000)
    }
})
